server:
  port: 8787

spring:
  application:
    name: aws
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=public
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        stringtype: unspecified
  jpa:
    hibernate:
      ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

cloud:
  aws:
    credentials:
      access-key: ${AWS_KEY}
      secret-key: ${AWS_SECRET}
      token: ${AWS_TOKEN}
      account-id: ${ACCOUNT_ID}
    region:
      static: ${AWS_REGION}
      auto: false

sns:
  topic: ${SNS_TOPIC}

sqs:
  queue-name-consumer: ${SQS_QUEUE}

s3:
  bucket-video-original: ${S3_BUCKET_VIDEO}
  bucket-frames: ${S3_BUCKET_ZIP}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, loggers
