server.port: 8000

spring:
  application.name: aws
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        stringtype: unspecified
  jpa:
    hibernate:
      ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_KEY}
      secret-key: ${AWS_SECRET}
      token: ${AWS_TOKEN}
      account-id:
    region:
      static: us-east-1
      auto: false

sns:
  topic: video-carregado-topic.fifo

sqs:
  queue-name-consumer: video-status-subscriber-queue.fifo

S3:
  bucket-video-original: original-video-bucket
  bucket-frames: frames-video-bucket
