apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: upload-frame-flow
  name: upload-frame-flow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: upload-frame-flow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: upload-frame-flow
    spec:
      containers:
        - name: upload-frame-flow
          image: 090111931170.dkr.ecr.us-east-1.amazonaws.com/upload-frame-flow
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: AWS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: AWS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: AWS_SECRET
            - name: AWS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: AWS_TOKEN
            - name: ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: ACCOUNT_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: AWS_REGION
            - name: SNS_TOPIC
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: SNS_TOPIC
            - name: SQS_QUEUE
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: SQS_QUEUE
            - name: S3_BUCKET_ZIP
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: S3_BUCKET_ZIP
            - name: S3_BUCKET_VIDEO
              valueFrom:
                secretKeyRef:
                  name: secret-frameflow-upload
                  key: S3_BUCKET_VIDEO
          livenessProbe:
            httpGet:
              path: /manage/health
              port: 8787
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /manage/health
              port: 8787
            initialDelaySeconds: 60
            periodSeconds: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
