apiVersion: v1
items:
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: upload-frame-flow
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: upload-frame-flow
      minReplicas: 1
      maxReplicas: 10
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
kind: List
metadata:
  resourceVersion: ""
